version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  release_notes_automation:
    docker:
      - image: circleci/node:lts
    working_directory: ~/app
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run release-notes-automation

workflows:
  wk_prod:
    jobs:
      - release_notes_automation:
        filters:
            branches:
              only:
                - production
