version: 2.1
orbs:
  node: circleci/node@4.7

jobs:
  release_notes_automation:
    docker:
      - image: circleci/node:lts
    working_directory: ~/creepy-stories/web
    steps:
      - checkout
      - run: npm run build
      - run: npm run release-notes-automation

workflows:
  wk_prod:
    jobs:
      - release_notes_automation:
        filters:
            branches:
              only:
                - production